#!/usr/bin/env pwsh
# Build A Keepers Need 2 (BepInEx plugin). After a successful build it locates the
# game's install folder through Steam (no hard-coded machine path) and, if a
# BepInEx\plugins folder is present there, copies the DLL in. Pass -NoDeploy to skip.
#
# Usage:
#   ./build.ps1                 # Debug build + deploy
#   ./build.ps1 -Configuration Release
#   ./build.ps1 -Clean          # clean before building
#   ./build.ps1 -NoDeploy       # build only, don't copy to the game
#   ./build.ps1 -ManagedDir <dir> -Version 1.2.3   # explicit game DLL folder + version (CI)

[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Debug',
    [switch]$Clean,
    [switch]$NoDeploy,
    [string]$ManagedDir,
    [string]$Version
)

$ErrorActionPreference = 'Stop'
$project = Join-Path $PSScriptRoot 'AKeepersNeed2.csproj'
$AppId = '4358690'  # Graveyard Keeper 2 on Steam

# Resolves the game's install folder via Steam instead of a hard-coded path:
# HKCU SteamPath -> steamapps\libraryfolders.vdf (all library roots) -> the library
# whose steamapps\appmanifest_<AppId>.acf exists -> its "installdir" under common\.
# Returns $null if Steam, the game, or any step can't be found.
function Resolve-GamePath {
    param([string]$AppId)

    try {
        $steamPath = (Get-ItemProperty -Path 'HKCU:\Software\Valve\Steam' -ErrorAction Stop).SteamPath
    } catch {
        return $null
    }
    if (-not $steamPath) {
        return $null
    }

    $vdf = Join-Path $steamPath 'steamapps\libraryfolders.vdf'
    if (-not (Test-Path $vdf)) {
        return $null
    }

    $libraries = @($steamPath)
    Select-String -Path $vdf -Pattern '"path"\s+"([^"]+)"' | ForEach-Object {
        $libraries += ($_.Matches[0].Groups[1].Value -replace '\\\\', '\')
    }

    foreach ($lib in ($libraries | Select-Object -Unique)) {
        $manifest = Join-Path $lib "steamapps\appmanifest_$AppId.acf"
        if (Test-Path $manifest) {
            $content = Get-Content $manifest -Raw
            if ($content -match '"installdir"\s+"([^"]+)"') {
                return Join-Path $lib "steamapps\common\$($Matches[1])"
            }
        }
    }
    return $null
}

# The game's managed DLLs are copyrighted and not in the repo, so their <Reference>
# items live in a local, git-ignored GameReferences.props. Generate it from the installed
# game when it's absent; an existing file is left untouched so you can point it elsewhere.
function Initialize-GameReferences {
    $props = Join-Path $PSScriptRoot 'GameReferences.props'
    if (Test-Path $props) {
        return
    }
    if ($ManagedDir) {
        if (-not (Test-Path $ManagedDir)) {
            Write-Host "-ManagedDir not found: $ManagedDir" -ForegroundColor Yellow
            return
        }
        $managed = (Resolve-Path $ManagedDir).Path
    } else {
        $gamePath = Resolve-GamePath -AppId $AppId
        if (-not $gamePath) {
            Write-Host "GameReferences.props missing and the game wasn't found via Steam." -ForegroundColor Yellow
            Write-Host "Create it manually (see README.md) before building." -ForegroundColor Yellow
            return
        }
        $managed = Join-Path $gamePath 'GraveyardKeeper2_Data\Managed'
        if (-not (Test-Path $managed)) {
            Write-Host "Found the game but not its Managed folder: $managed" -ForegroundColor Yellow
            return
        }
    }
    $template = @'
<Project>
  <!-- Machine-local, generated by build.ps1 and git-ignored. Edit GameManagedDir if you
       keep the game's copyrighted managed DLLs somewhere else. -->
  <PropertyGroup>
    <GameManagedDir>__MANAGED__</GameManagedDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(GameManagedDir)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LazyBearTechnology">
      <HintPath>$(GameManagedDir)\LazyBearTechnology.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
'@
    ($template -replace '__MANAGED__', $managed) | Set-Content -Path $props -Encoding UTF8
    Write-Host "Generated GameReferences.props -> $managed" -ForegroundColor Green
}

# Referencing the game's Unity assemblies (which target netstandard 2.1) from a
# net461 plugin floods the log with MSB3277 netstandard-version conflict warnings.
# They're harmless here — BepInEx/Mono supplies the runtime assemblies — so demote
# them to messages for this build only, rather than touching the csproj.
$suppress = '-p:MSBuildWarningsAsMessages=MSB3277'
$buildArgs = @($suppress)
if ($Version) {
    $buildArgs += "-p:Version=$Version"
}

if ($Clean) {
    Write-Host "Cleaning ($Configuration)..." -ForegroundColor Cyan
    dotnet clean $project -c $Configuration --nologo -v minimal $suppress
}

Initialize-GameReferences

Write-Host "Building $Configuration..." -ForegroundColor Cyan
dotnet build $project -c $Configuration --nologo -v minimal @buildArgs
if ($LASTEXITCODE -ne 0) {
    Write-Host "Build FAILED (exit $LASTEXITCODE)." -ForegroundColor Red
    exit $LASTEXITCODE
}

$dll = Join-Path $PSScriptRoot "bin\$Configuration\net461\AKeepersNeed2.dll"
if (-not (Test-Path $dll)) {
    Write-Host "Build reported success but DLL not found at expected path:" -ForegroundColor Red
    Write-Host "  $dll"
    exit 1
}

Write-Host "Output: $dll"

if ($NoDeploy) {
    return
}

$gamePath = Resolve-GamePath -AppId $AppId
if (-not $gamePath) {
    Write-Host "Could not locate the game via Steam; copy the DLL into <game>\BepInEx\plugins\ manually." -ForegroundColor Yellow
    return
}

$plugins = Join-Path $gamePath 'BepInEx\plugins'
if (-not (Test-Path $plugins)) {
    Write-Host "Found the game but no BepInEx\plugins folder (is BepInEx installed?):" -ForegroundColor Yellow
    Write-Host "  $gamePath"
    return
}

Write-Host ""
Write-Host "Deploy target: $plugins" -ForegroundColor Cyan
$answer = Read-Host "Copy the DLL there now? [y/N]"
if ($answer -match '^(y|yes)$') {
    Copy-Item -Path $dll -Destination $plugins -Force
    Write-Host "Deployed to: $plugins" -ForegroundColor Green
} else {
    Write-Host "Skipped deploy." -ForegroundColor Yellow
}
